image: gitpod/workspace-full

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ecmel.vscode-html-css
    - ritwickdey.LiveServer
