version: '3.8'
services:
  app:
    image: node:22
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm install && npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development